version: '2.1'
services:

  base:
    image: '${REGISTRY_HOST}${REGISTRY_URI}-base:v1.0.4'
    # env_file:
    #   - .env
    #   - .env.development
    environment:
      POSTGRES_DB: blacklight_yul_development
      POSTGRES_HOST: db_blacklight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    build:
      context: .
      dockerfile: Dockerfile.base

  blacklight:
    build: .
    image: '${REGISTRY_HOST}${REGISTRY_URI}:master'
    # env_file:
    #   - .env
    #   - .env.development
    environment:
      POSTGRES_DB: blacklight_yul_development
      POSTGRES_HOST: db_blacklight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SOLR_URL: http://solr:8983/solr/blacklight-core
      IIIF_MANIFESTS_BASE_URL: /manifests/
      PASSENGER_APP_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - blacklight:/home/app/webapp
    command: bash -c "echo $$(date -u +%FT%TZ) > DEPLOYED_AT && /sbin/my_init"
    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    depends_on:
    depends_on:
      - db_blacklight
      - solr
      - iiif_manifest
      - iiif_image


  management:
    image: yalelibraryit/dc-management:${MANAGEMENT_VERSION}
    env_file:
      - .env
      - .secrets
    environment:
      POSTGRES_DB: yul_dc_management_development
      POSTGRES_HOST: db_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SOLR_URL: http://solr:8983/solr
      SOLR_CORE: blacklight-core
      PASSENGER_APP_ENV: development
    ports:
      - "3001:3000"
    depends_on:
      - db_management
      - solr

  db_blacklight:
    image: postgres:${POSTGRES_VERSION}
    env_file:
      - .env
    environment:
      POSTGRES_DB: blacklight_yul_development
      POSTGRES_HOST: db_blacklight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - "db_blacklight:/var/lib/postgresql/data"

  db_management:
    image: postgres:${POSTGRES_VERSION}
    env_file:
      - .env
    environment:
      POSTGRES_DB: yul_dc_management_development
      POSTGRES_HOST: db_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - "db_management:/var/lib/postgresql/data"


  solr:
    image: yalelibraryit/dc-solr:${SOLR_VERSION}
    ports:
      - '8983:8983'
    volumes:
      # think this may need to be changed to /var/solr/data
      - solr:/opt/solr/server/solr/mycores
    env_file:
      - .env
    command: bash -c 'precreate-core ${SOLR_CORE} /opt/config; precreate-core ${SOLR_TEST_CORE} /opt/config; exec solr -f'

  iiif_image:
    image: yalelibraryit/dc-iiif-cantaloupe:${IIIF_IMAGE_VERSION:-latest}
    env_file:
      - .env
    ports:
      - '8182:8182'

  iiif_manifest:
    image: yalelibraryit/dc-iiif-manifest:${IIIF_MANIFEST_VERSION:-latest}
    ports:
      - '80:80'

volumes:
  postgres:
  solr:
  blacklight:
  db_blacklight:
  db_management:
