version: '2.1'
services:

  base:
    image: '${REGISTRY_HOST}${REGISTRY_URI}-base:v1.0.0'
    env_file:
      - .env
      - .env.development
    build:
      context: .
      dockerfile: Dockerfile.base

  web:
    build: .
    image: '${REGISTRY_HOST}${REGISTRY_URI}:master'
    env_file:
      - .env
      - .env.development
    ports:
      - '3000:3000'
    volumes:
      - .:/home/app/webapp
    # command: bash -c "date > DEPLOYED_AT && /sbin/my_init"
    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    depends_on:
      - solr
      - db
      - iiif_image
      - iiif_manifest

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'


  solr:
    image: yalelibraryit/dc-solr:${SOLR_TAG:-latest}
    ports:
      - '8983:8983'
    volumes:
      # think this may need to be changed to /var/solr/data
      - solr:/opt/solr/server/solr/mycores
    env_file:
      - .env
    command: bash -c 'precreate-core ${SOLR_CORE} /opt/config; precreate-core ${SOLR_TEST_CORE} /opt/config; exec solr -f'

  iiif_image:
    image: yalelibraryit/dc-iiif-cantaloupe:${IIIF_IMAGE_VERSION:-latest}
    env_file:
      - .env
    ports:
      - '8182:8182'

  iiif_manifest:
    image: yalelibraryit/dc-iiif-manifest:${IIIF_MANIFEST_VERSION:-latest}
    ports:
      - '80:80'

volumes:
  postgres:
  solr:
