author_tsim: 'Author'
author_vern_ssim: 'Author'
coordinates_ssim: 'Coordinates'
copyrightDate_ssim: 'Copyright Date'
date_ssim: 'Date'
digital_ssim: 'Digital'
edition_ssim: 'Edition'
language_ssim: 'Language'
publicationPlace_ssim: 'Publication Place'
publisher_ssim: 'Publisher'
published_ssim: 'Published'
published_vern_ssim: 'Published'
sourceCreated_tesim: 'Source Created'
sourceDate_tesim: 'Source Date'
sourceEdition_tesim: 'Source Edition'
sourceNote_tesim: 'Source Note'
sourceTitle_tesim: 'Source Title'
